[package]
name = "upgraderail-simulator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
stellar-xdr.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
upgraderail-core = { path = "../upgraderail-core" }

[lints]
workspace = true
