[package]
name = "upgraderail-wasm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
soroban-spec.workspace = true
stellar-xdr.workspace = true
thiserror.workspace = true
upgraderail-core = { path = "../upgraderail-core" }
wasmparser.workspace = true

[dev-dependencies]
tempfile = "3.23.0"

[lints]
workspace = true

